### ISSUE TITLE
Cant post Bot info

### ISSUE THREAD

**Issue by dsezerpy** [dclist/python-sdk#1]
I cant post stats of my bot while using the code in `README.md`.

`{"message": "Variable "$stats" got invalid value null at "stats.userCount"; Expected non-nullable type "Int!" not to be null.", "locations": [{"line": 1, "column": 23}], "extensions": {"code": "INTERNAL_SERVER_ERROR"}} (status code: {"message": "Variable "$stats" got invalid value null at "stats.userCount"; Expected non-nullable type "Int!" not to be null.", "locations": [{"line": 1, "column": 23}], "extensions": {"code": "INTERNAL_SERVER_ERROR"}})`

**Comment by dsezerpy** [comment]
Fixed by myself.

**Comment by ilkergzlkkr** [comment]
I did hardcoded the [shard_count](https://github.com/dclist/python-sdk/blob/46dc11f7646adfd8842d1dade4ed41b8929fe320/dclist/gqlhttp.py#L92) but not worked lol.

Shard count isn't a index so it needs to be at least `1` not `0` so. thx for the commit tho.

**Comment by ilkergzlkkr** [comment]
Oh error was not the Shard count, hardcode working well. I reproduced the error.
Error was [userCount](https://github.com/dclist/python-sdk/blob/46dc11f7646adfd8842d1dade4ed41b8929fe320/dclist/client.py#L82-L83) which is i overlooked.
